<?php


namespace Transave\CommonBase\Tests\Feature\Flutterwave;


use Transave\CommonBase\Actions\Flutterwave\VerifyAndCreateTransaction;
use Transave\CommonBase\Tests\TestCase;

class VerifyTransactionTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    function can_verify_transaction_by_transfer_reference()
    {
        $response = (new VerifyAndCreateTransaction(['tx_ref' => 'dfs23fhr7ntg0293039_PMCK']))->execute();
        dd($response);
    }
}