<?php


namespace Transave\CommonBase\Tests\Feature\Kuda\Transfer;


use Transave\CommonBase\Actions\Kuda\Transfer\BankList;
use Transave\CommonBase\Tests\TestCase;

class BankListTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    function can_retrieve_bank_list_successfully()
    {
        $response = (new BankList())->execute();
        $array = json_decode($response->getContent(), true);
        $this->assertEquals(true, $array['success']);
        $this->assertNotNull($array['data']);
    }
}